#!/bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

mkdir -p ${DESTDIR}/lib/firmware
cp -a /lib/firmware/rgx.sh.* ${DESTDIR}/lib/firmware
cp -a /lib/firmware/rgx.fw.* ${DESTDIR}/lib/firmware
