#! /usr/bin/dh-exec

bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/usr/lib/libGLESv1_CM_PVR_MESA.so* usr/lib/${DEB_HOST_MULTIARCH}/
bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/usr/lib/libGLESv2_PVR_MESA.so* usr/lib/${DEB_HOST_MULTIARCH}/
bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/usr/lib/libglslcompiler.so* usr/lib/${DEB_HOST_MULTIARCH}/
bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/usr/lib/libpvr_dri_support.so* usr/lib/${DEB_HOST_MULTIARCH}/
bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/usr/lib/libPVROCL.so* usr/lib/${DEB_HOST_MULTIARCH}/
bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/usr/lib/libPVRScopeServices.so* usr/lib/${DEB_HOST_MULTIARCH}/
bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/usr/lib/libsrv_um.so* usr/lib/${DEB_HOST_MULTIARCH}/
bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/usr/lib/libsutu_display.so* usr/lib/${DEB_HOST_MULTIARCH}/
bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/usr/lib/libufwriter.so* usr/lib/${DEB_HOST_MULTIARCH}/
bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/usr/lib/libusc.so* usr/lib/${DEB_HOST_MULTIARCH}/
bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/usr/lib/libVK_IMG.so* usr/lib/${DEB_HOST_MULTIARCH}/

bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/etc/vulkan/icd.d/icdconf.json usr/share/vulkan/icd.d/pvr.json
bin/ddk119/36.50.54.182/${DEB_BUILD_ARCH}/etc/OpenCL usr/share/
